### ISSUE TITLE
Unicode font

### ISSUE THREAD

**Issue by exodius48** [Magisk-Modules-Repo/Fontchanger#10]
Does possible to include these unicode font: https://www.4shared.com/folder/vl190bPg/Font_v8.html
It support to display unicode icon, autotext, simbol unicode, etc etc

**Comment by JohnFawkes** [comment]
I won't be including any more fonts since there are already 244 fonts and I'm working on a way to streamline the process of providing your own. there are just too many fonts that are non-redistributable and I cant include those
