### ISSUE TITLE
Make Font Changer's Magisk Manager module searchable with the search term "emoji"

### ISSUE THREAD

**Issue by DandelionSprout** [Magisk-Modules-Repo/Fontchanger#13]
Okay, so I know that this situation is through absolutely zero fault of your own, but essentially John Wu removed a lot of emoji fonts from the Magisk repo within the past week (According to him it was to remove download list clutter), and pointed people towards your project specifically on his Twitter feed ([Tweet 1](https://twitter.com/topjohnwu/status/1229896206584664065), [tweet 2](https://twitter.com/topjohnwu/status/1229910209776078848)).

However, as this turn of events does not seem to me to have been announced elsewhere on the internet (that I know of) at the time of writing, this has and/or will lead to confusion when people type "emoji" in the Magisk download search bar and only get \~2 results (Neither of which are Font Changer) instead of the previous 20\~25 (I know I was confused for ~15min), so I think there's a pretty good opportunity both for major publicity gains and for confusion resolvement if you add the word *emoji* somewhere within either the title or the synopsis in Font Changer's Magisk Manager download list entry.

**Comment by JohnFawkes** [comment]
the title will be difficult but I can add the word emoji to the description and that will make it searchable. good idea. thanks
