### ISSUE TITLE
Could you add times new roman to the font list? 

### ISSUE THREAD

**Issue by yourbestbob** [Magisk-Modules-Repo/Fontchanger#17]
The most euphoric font of them all
I shan't download telegram. 
Custom said that the folder was empty the entire time. I'm probably doing something wrong. But this method is fine too, giving u a head start :) 
[Times.zip](https://github.com/Magisk-Modules-Repo/Fontchanger/files/4405857/Times.zip)

**Comment by JohnFawkes** [comment]
If you follow https://github.com/johnfawkes/android_font_patcher you can add fonts yourself

**Comment by yourbestbob** [comment]
Well apparently not as easy as it seems. Followed the instructions multiple times accordingly, but tells me at the latest command constantly that I my folder is empty
![Screenshot_20200409-162520_Termux](https://user-images.githubusercontent.com/62913885/78923800-13438b00-7a99-11ea-8816-6a32a57d2bd4.jpg)

**Comment by JohnFawkes** [comment]
You likely only placed the ttf inside the patcher folder. it needs to go in a folder in the patcher folder

**Comment by yourbestbob** [comment]
> You likely only placed the ttf inside the patcher folder. it needs to go in a folder in the patcher folder

Nope, already did that
