### ISSUE TITLE
Custom Emojis do not Display on Gboard when using WhatsApp

### ISSUE THREAD

**Issue by DavidBerdik** [Magisk-Modules-Repo/Fontchanger#18]
Hello @JohnFawkes,

I have configured my device to use the blob emoji set. This is working fine and the blob emojis appear on Gboard as intended.

![Screenshot_20200402-171643_Pixel_Launcher](https://user-images.githubusercontent.com/7663225/78302026-0b6b7000-7508-11ea-8ee4-179532e9d573.png)

When I use WhatsApp however, the original emojis display on the keyboard instead.

![Screenshot_20200402-171656_WhatsApp](https://user-images.githubusercontent.com/7663225/78302095-2b029880-7508-11ea-9913-98e21f256c38.png)

I first ran in to this issue on my Pixel 3 XL running the March 2020 Android 10 update (the latest release as of this posting). To determine if this issue was limited to my device, I installed Fontchanger and WhatsApp on my old Nexus 6 running the April 1, 2020 build of LineageOS 16.0 (Android Pie) and was able to reproduce the issue. The screenshots I have included in this issue post were taken on the Nexus 6.

Thank you,
David

**Comment by JohnFawkes** [comment]
This isn't a fontchanger issue. It's a gboard issue. Revert to an older build of gboard and the issue will disappear

**Comment by DavidBerdik** [comment]
@JohnFawkes Very well. Thank you. I take it you have seen this issue then as well?

**Comment by JohnFawkes** [comment]
Me personally no. I run the beta build of gboard just fine but some users have to go back to 8.8 gboard and the issue is gone

**Comment by DavidBerdik** [comment]
@JohnFawkes Okay. Thank you for providing a solution. 😊
