### ISSUE TITLE
Custom Help is blank

### ISSUE THREAD

**Issue by uudruid74** [Magisk-Modules-Repo/Fontchanger#20]
Font customization help does nothing.  No instructions on github.  Really don't want to read the scripts myself.

![Screenshot_20200410-192305](https://user-images.githubusercontent.com/7726301/79030908-038f7980-7b61-11ea-9382-2707fac7e59b.jpg)

**Comment by JohnFawkes** [comment]
https://github.com/johnfawkes/android_font_patcher

If you use one single ttf for custom font then use the above link. 


If you have all the roboto-* ttfs then just make a folder in internal storage/Fontchanger/Fonts/Custom and then place the ttfs in that folder. 


After doing either step above run su font_changer and choose fonts then custom

**Comment by JohnFawkes** [comment]
also it looks like you might be on an older build maybe. custom help option is working fine here.
