### ISSUE TITLE
Custom font won't apply

### ISSUE THREAD

**Issue by gitfont1** [Magisk-Modules-Repo/Fontchanger#4]
I have my custom font in the proper directory, even added all the Google fonts, but the fontchanger keeps saying it can't find the fonts. I'm not sure what the problem is. I just flashed the full update for my phone and redid TWRP/Magisk, and now all of a sudden the font won't apply, whereas it did work before the update.

**Comment by JohnFawkes** [comment]
I need more info that this. Logs or something. If you have telegram it would be much easier to join the group and send logs there
