### ISSUE TITLE
Module not able to update 

### ISSUE THREAD

**Issue by TheExoduser** [Magisk-Modules-Repo/Fontchanger#5]
Hey there,

not an issue with the module itself, rather an issue with the new check routine for conflicting modules.
Since the newest version (2.5.4.2 at the time of writing) now checks for font editing modules,
it is no longer able to auto update itself because the installation gets aborted with:

> Checking for any other font modules installed...
> [!] 
> [!] Module editing fonts detected [!]
> [!] Module - Font Changer [!]
> [!]

Since this requires the user to uninstall the module, then reboot, then install the new version and then reboot again, I think for ease of use there should be an exception in the module check routine for the module itself.

**Comment by JohnFawkes** [comment]
This should of been fixed. And you shouldn't have to uninstall to update. There's already a check for itself in the code
