### ISSUE TITLE
/system/bin/sh: font_changer: inaccessible or not found

### ISSUE THREAD

**Issue by Ways22** [Magisk-Modules-Repo/Fontchanger#9]
I've used font_changer previously on the same device and it worked quite well. I recently wiped my phone and reinstalled my rom and tried using font_changer but I get an error

`/system/bin/sh: font_changer: inaccessible or not found`

Device: xiaomi Redmi 8a on havocos 3.1 gsi

**Comment by JohnFawkes** [comment]
> I've used font_changer previously on the same device and it worked quite well. I recently wiped my phone and reinstalled my rom and tried using font_changer but I get an error
> 
> `/system/bin/sh: font_changer: inaccessible or not found`
> 
> Device: xiaomi Redmi 8a on havocos 3.1 gsi

should be fixed in latest version
